### ISSUE TITLE
Tds.Error expects the parameter '@1', which was not supplied.

### ISSUE THREAD

**Issue by bossyang** [livehelpnow/tds_ecto#35]
This will work without passing variable to the where condition.

``` elixir
     emp_name = "Mary"
     employee = Bot.Repo.one(
        from u in "bpm_user_dept_v",
        where: u.fpena == ^emp_name,
        select: %{dept: u.fdena, workno: u.fpeno}                                              
        )
```

```
15:29:58.552 [error] Task #PID<0.230.0> started from #PID<0.203.0> terminating
** (Tds.Error) 0 (8178): The parameterized query '(@1 varbinary(8))SELECT b0.[fdeno] FROM [bpm_user_dept_v] AS b0 ' expects the parameter '@1', which was not supplied.
    (ecto) lib/ecto/adapters/sql.ex:185: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/sql.ex:478: Ecto.Adapters.SQL.execute/6
    (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4
    (bot) lib/bot/responders/workno.ex:15: Bot.Responders.Workno.hear_1/2
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
Function: #Function<2.88939009/0 in Hedwig.Responder.run_async/2>
    Args: []
```

**Comment by mjaric** [comment]
fixed in master
