### ISSUE TITLE
Connections Die after Many Days

### ISSUE THREAD

**Issue by trbngr** [livehelpnow/tds_ecto#71]
We have a service running tds_ecto that will run for days on end no problem and then will just stop connecting to the DB.

After that, the logs will be full of the following:
```
[error] GenServer #PID<0.15718.16> terminating
** (DBConnection.ConnectionError) connection is closed
(tds) lib/tds/protocol.ex:869: Tds.Protocol.msg_recv/2
(tds) lib/tds/protocol.ex:810: Tds.Protocol.msg_send/2
(tds) lib/tds/protocol.ex:493: Tds.Protocol.send_query/2
(tds) lib/tds/protocol.ex:81: Tds.Protocol.ping/1
(db_connection) lib/db_connection/connection.ex:373: DBConnection.Connection.handle_info/2
(connection) lib/connection.ex:810: Connection.handle_async/3
(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Last message: :timeout```

Is this a known issue?

Thanks,
Chris

**Comment by mjaric** [comment]
this is not known to me. What OTP and elixir version  you are using?
